## PAPER WALKTHROUGH 

In [1]:
import numpy as np


import sys
import os

sys.path.append(os.path.abspath("../src"))

In [2]:
from batchnorm import BatchNorm

In [4]:
x = np.random.normal(loc=100,scale=25,size=(32,5))

print(f"This is the shape of our input data: {x.shape}")



This is the shape of our input data: (32, 5)


In [5]:
batch = BatchNorm()
scaled_x = batch.forward(x)

print(f"this is the shape of scaled_x: {scaled_x.shape}")

print(f"This is the scaled_x: {scaled_x}")

this is the shape of scaled_x: (32, 5)
This is the scaled_x: [[-2.07713588  0.85685929 -1.01840238  2.45291271 -2.39661977]
 [ 1.05937992 -1.02085306  0.55508848  2.30792855  0.67089127]
 [-0.00538362 -0.46100101  0.68944336 -1.01286726  1.10790054]
 [-0.06704547 -0.16212633  0.28911082 -1.23335767  0.75454241]
 [-0.46439085 -0.55228123  0.16491279 -0.4337117   0.3963006 ]
 [ 0.97837892 -0.75540023  1.02605742 -0.03527992  1.11439314]
 [-0.38275827  0.54985964 -0.39116879  0.80110334 -1.79261518]
 [-0.3000031  -0.04190899 -1.02341295 -0.20052223  0.41877707]
 [-0.3916695  -1.00993036  0.31951099  0.18576786  1.38950364]
 [-1.19269042 -0.2953705   2.90456115 -0.76720176 -0.30062371]
 [ 1.17322218  0.17148018  1.10980129 -1.11874745  0.4854497 ]
 [ 0.76298969  0.28693297  1.30201495 -0.46442602  0.68853734]
 [-1.87294856 -1.03421815 -0.20763425 -1.31812852 -1.50915909]
 [-1.09152863  0.41022132 -0.38289467 -0.40812471  1.05272399]
 [-0.99099599  0.07589618 -0.60634976  0.33962131 -0.0297

In [6]:
print(f"The mean is this: {np.mean(scaled_x)}")
print(f"The variance is this: {np.var(scaled_x)}")


The mean is this: 1.1102230246251565e-16
The variance is this: 0.9999999819286515
